# Generated by Django 2.2.6 on 2019-10-11 11:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191011_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=200, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
