# Generated by Django 2.2.6 on 2019-10-11 11:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191011_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
