# Generated by Django 2.2.6 on 2019-10-11 12:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191011_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
